config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "photos#index"

  get "home", action: :show, controller: "home"

  resources :photos do
    resources :likes, only: [:create]
    resources :comments
  end

  resources :users do
    resources :subscribes, only: [:create]
  end

  resources :likes, only: [:index]
  resources :users, only: [:edit, :update]
  resources :profiles, only: [:show]
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :photo
    belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
    
    def index
        @likes = Like.includes(:user, :photo).where(photo_id: Photo.where(user_id: current_user.id)).order(created_at: :desc)
    end

    def create
        photo = Photo.find(params[:photo_id])

        if photo.likes.find_by(user: current_user).present?
            photo.likes.find_by(user: current_user).destroy
            photo.update(likes_count: photo.likes_count - 1)
        else
            photo.likes.create(user: current_user)
            photo.update(likes_count: photo.likes_count + 1)
        end

        redirect_back(fallback_location: root_path)
    end
end

app/helpers/likes_helper.rb
module LikesHelper
    def show_like photo, user
        if photo.likes.find_by(user: user).present?
            image = "heart-fill.svg"
        else
            image = "heart.svg"
        end

        image_tag("icons/#{image}", size: "24", class: "like-button")
    end
end

app/views/likes/_like.html.erb
<div class="columns is-mobile is-vcentered mb-0">
  <div class="column is-narrow pb-0">
    <%= link_to (show_user_avatar like.user, 40), profile_path(like.user) %>
  </div>
  <div class="column pb-0">
    <p class="has-text-weight-semibold is-inline"><%= link_to like.user.username, profile_path(like.user), style: "color: black" %></p><p class="is-inline"><%= t("like.liked") %></p>
  </div>
  <div class="column is-narrow pb-0">
    <%= link_to (image_tag(like.photo.images.first.variant(resize_to_fill: [40, 40]))), photo_path(like.photo), data: {turbo: false} %>
  </div>
</div>

app/views/likes/index.html.erb
<div class="columns is-mobile is-centered mt-3">
  <div class="column is-4-desktop is-12-tablet is-12-mobile">
    <div class="box">
      <%= render @likes %>
    </div>
  </div>
</div>