config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "photos#index"

  get "home", action: :show, controller: "home"

  resources :photos do
    resources :likes, only: [:create]
    resources :comments
  end

  resources :users do
    resources :subscribes, only: [:create]
  end

  resources :likes, only: [:index]
  resources :users, only: [:edit, :update]
  resources :profiles, only: [:show]
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many_attached :images
  has_many :hashtags, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :last_comments, -> { limit(3) }, class_name: 'Comment'

  validates :text, length: { maximum: 1200 }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!

  before_action do
    ActiveStorage::Current.url_options = { protocol: request.protocol, host: request.host, port: request.port }
  end

  def index
    @posts = Photo.includes(:user, :likes).where(user_id: current_user.subscribes.pluck(:user_subscribe)).order(created_at: :desc)
  end

  def show
    @photo = Photo.includes(:user, :likes, comments: [:user]).find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id     

    if @photo.images.attached? && @photo.valid?
      @photo.save

      hashtags = helpers.hashtag_parser photo_params[:text]
      hashtags.each { |hashtag| @photo.hashtags.create(text: hashtag.downcase) }

      redirect_to @photo
    else
      flash[:alert] = helpers.new_photo_error @photo
      render action: "new", status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def photo_params
    params.require(:photo).permit(:text, images: [])
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
    def new_photo_error(photo)
        if photo.invalid?
            t("errors.new_photo.text_invalid")
        else
            t("errors.new_photo.photo_missing")
        end
    end

    def show_all_photo(photo)
        link_to (image_tag(photo.images.first.variant(resize_to_fill: [700, 700]))), photo_path(photo), data: {turbo: false}, style: "display: flex"
    end

    def text_parser(string)
        hashtag_rule = /(#[[:word:]]+)/
        text = []

        string.split(hashtag_rule).each do |word|
            if word.match?(hashtag_rule)
                text << "<a href='#{root_url}'>" + word + "</a>"
            else
                text << word
            end
        end
        text.join.html_safe
    end

    def hashtag_parser(text)
        text.scan(/#[[:word:]]+/).uniq
    end
end

app/views/photos/_header.html.erb
<div class="custom-header">
  <div class="columns is-gapless is-mobile is-vcentered">
    <div class="column is-narrow" style="display: flex">
      <div class="ml-1" style="display: flex"><%= show_user_avatar photo.user, 40 %></div>
    </div>
    <div class="column is-narrow">
      <p class="has-text-weight-semibold is-size-5 pl-2"><%= link_to photo.user.username, profile_path(photo.user), style: "color: black" %></p>
    </div>
  </div>
</div>

app/views/photos/_likes.html.erb
<div class="columns is-gapless is-mobile is-vcentered mb-1">
  <div class="column is-narrow" style="display: flex">
    <%= form_for :like, url: photo_likes_path(photo) do |f| %>
      <%= f.button (show_like photo, current_user), type: "submit", class: "icon-button", style: "cursor: pointer" %>
    <% end %>
  </div>
  <div class="column is-narrow">
    <p class="has-text-weight-semibold is-size-6 pt-1" style="color: black"><%= t("show_photo.likes") + (separator photo.likes_count).to_s %></p>
  </div>
</div>

app/views/photos/_photo.html.erb
<div class="column is-4-desktop is-4-tablet is-4-mobile padding-025">
  <div class="box padding-none">
    <%= show_all_photo photo %>
  </div>
</div>

app/views/photos/_post.html.erb
<div class="box padding-none">
  <%= render "header", photo: post %>
  <div class="column is-12-desktop is-12-tablet is-12-mobile show-box padding-none">
    <%= image_tag(post.images.first) %>
  </div>
  <turbo-frame id="likes_<%= post.id %>">
    <%= render "likes", photo: post %>
  </turbo-frame>
  <%= render "text", photo: post %>
  <div class="columns is-mobile mb-0">
    <div class="column pt-2">
      <%= link_to post_comments(post), photo_path(post), data: { turbo: false }, class: "all_comments_link pl-3" %>
    </div>
  </div>
  <%= render partial: "comments/post_comment", collection: post.last_comments %>
</div>

app/views/photos/_slide.html.erb
<div class="slide" style="display: block;">
  <%= image_tag(slide, class: "show-photo") %>
</div>

app/views/photos/_text.html.erb
<div class="is-size-6-5 pl-3 pr-3 mb-3"><%= text_parser photo.text %></div>

app/views/photos/index.html.erb
<div class="columns is-mobile is-centered mt-3">
  <div class="column is-4-desktop is-12-tablet is-12-mobile">
    <% if @posts.present? %>
      <%= render partial: "photos/post", collection: @posts %>
    <% else %>
      <div class="top-margin-20">
        <p style="text-align: center"><%= t("photo_index.subscribe") %></p>
        <p style="text-align: center"><%= link_to t("photo_index.new_people"), home_url %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/photos/new.html.erb
<div class="columns is-mobile is-centered top-margin-5">
  <div class="column is-10-desktop is-12-mobile">
    <div class="box padding-none">
      <%= form_for :photo, url: photos_path do |f| %>
        <div class="custom-header">
          <div class="columns is-mobile">
            <div class="column is-6">
              <%= f.label :images, t("new_photo_page.add_images"), class: "button is-small is-info" %>
              <%= f.file_field :images, multiple: true, style: "display: none" %>
            </div>
            <div class="column is-6">
              <%= f.button t("new_photo_page.submit"), type: "submit", class: "button is-small is-info", style: "float:right" %>
            </div>
          </div>
        </div>
        <div class="columns is-gapless">
          <div class="column is-6-desktop is-12-mibile pb-0">
            <div class="image-preview" style="position: relative;">
              <%= image_tag("icons/image-fill.svg", size: "50", class: "new-photo-icon") %>
              <p class="new-photo-icon mt-5"><%= t("new_photo_page.add_photo") %></p>
            </div>
          </div>
          <div class="column is-6-desktop is-12-mibile">
            <%= f.text_area :text, rows: "1", autocomplite: :off, placeholder: t("new_photo_page.placeholder"), id: "resize-textarea", class: "text-area-photo new-photo-text" %>
            <p class="has-text-weight-semibold mb-3" style="text-align: center; color: rgb(130,130,130)"><%= flash[:alert] %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/photos/show.html.erb
<div class="columns is-mobile is-centered mt-3">
  <div class="column is-10-desktop is-12-tablet is-12-mobile">
    <div class="box padding-none full-height-screen">
      <div class="columns is-mobile is-gapless is-multiline">
        <div class="column is-6-desktop is-12-tablet is-12-mobile pb-0 show-box full-height-screen">
          <%= render partial: "slide", collection: @photo.images %>
          <% unless @photo.images.size <= 1 %>
            <%= label_tag "previous-button", image_tag("chevron-compact-left.svg", size: "40", class: "slide-button previous-button") %>
            <%= button_tag "", onclick: "switchSlide(-1)", id: "previous-button", style: "display: none" %>
            <%= label_tag "next-button", image_tag("chevron-compact-right.svg", size: "40", class: "slide-button next-button") %>
            <%= button_tag "", onclick: "switchSlide(1)", id: "next-button", style: "display: none" %>
          <% end %>
        </div>
        <div class="column is-6-desktop is-12-tablet is-12-mobile show-contant" style="position: relative;">
          <%= render "header", photo: @photo %>
          <turbo-frame id="likes_<%= @photo.id %>">
            <%= render "likes", photo: @photo %>
          </turbo-frame>
          <div class="overflow comment-area scrollbar">
            <%= render "text", photo: @photo %>
            <turbo-frame id="comments">
              <p class="pl-3 pb-3"><%= separator(@photo.comments.size) + counter(@photo.comments.size, "comments_var") %></p>
              <%= render partial: "comments/comment", collection: @photo.comments.select { |comment| comment["parent_id"] == nil } %>
            </turbo-frame>
          </div>
          <%= render "comments/comment_form" %>
        </div>
      </div>
    </div>
  </div>
</div>