config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords'}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "photos#index"

  get "home", action: :show, controller: "home"

  resources :photos do
    resources :likes, only: [:create]
    resources :comments
  end

  resources :users do
    resources :subscribes, only: [:create]
  end

  resources :likes, only: [:index]
  resources :users, only: [:edit, :update]
  resources :profiles, only: [:show]
end

app/views/layouts/_navbar.html.erb
<nav class="custom-navbar">
  <div class="container is-fluid">
    <div class="custom-navbar-start">
      <%= link_to image_tag("Photoshare_mini.png", class: "navbar-logo"), root_url %>
    </div>
    <div class="custom-navbar-end" style="display: flex">
      <div class="is-hidden-mobile">
        <%= render "layouts/navbar_links" %>
      </div>
      <div class="custom-navbar-item is-hidden-desktop is-hidden-tablet">
        <div class="dropdown is-right" id="navbar">
          <%= button_tag image_tag("icons/list.svg", size: "24", class: "btn navbar-icon"), onclick: "dropdown('navbar')", class: "btn icon-button" %>
          <div class="dropdown-menu" role="menu">
            <div class="dropdown-content">
              <%= render "layouts/navbar_links" %>
            </div>
          </div>
        </div>
      </div>
      <%= render "layouts/profile_avatar" %>
    </div>
  </div>
</nav>

app/views/layouts/_navbar_links.html.erb
<div class="custom-navbar-item">
  <%= link_to image_tag("icons/house.svg", size: "24", class: "navbar-icon"), root_url %>
</div>
<div class="custom-navbar-item">
  <%= link_to image_tag("icons/envelope.svg", size: "24", class: "navbar-icon"), root_url %>
</div>
<div class="custom-navbar-item">
  <%= link_to image_tag("icons/compass.svg", size: "24", class: "navbar-icon"), home_url %>
</div>
<div class="custom-navbar-item">
  <%= link_to image_tag("icons/plus-square.svg", size: "24", class: "navbar-icon"), new_photo_url %>
</div>
<div class="custom-navbar-item">
  <%= link_to image_tag("icons/heart.svg", size: "24", class: "navbar-icon"), likes_url %>
</div>

app/views/layouts/_profile_avatar.html.erb
<div class="dropdown is-right" id="profile_button">
  <div class="custom-navbar-item">
    <%= button_tag (show_user_avatar current_user, 24, "btn navbar-profile-button"), onclick: "dropdown('profile_button')", class: "btn icon-button", style: "cursor: pointer" %>
  </div>
  <div class="dropdown-menu" role="menu">
    <div class="dropdown-content">
      <%= link_to t("navbar.profile"), profile_path(current_user), class: "dropdown-item" %>
      <%= link_to t("navbar.exit"), destroy_user_session_url, data: {turbo_method: :delete}, class: "dropdown-item", style: "color: rgb(255,56,96)" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="background-color">
  <head>
    <title>Photoshare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render "layouts/navbar" %>
    <% end %>
    <div class="container is-fluid">
      <%= yield %>
    </div>
  </body>
</html>